In [2]:
import pandas as pd

In [56]:
df=pd.read_csv('data.csv')

In [57]:
df.head()

,Fever,Body Pain,Age,Lost of smell or taste,Sore throat,headache,Difficulty in breathing,Infection probability
0,102,1,46,1,1,0,1,0
1,103,0,29,0,1,1,1,0
2,103,0,1,1,1,1,0,0
3,98,0,94,0,1,1,0,1
4,98,1,59,1,1,1,1,1

In [58]:
df.tail()

,Fever,Body Pain,Age,Lost of smell or taste,Sore throat,headache,Difficulty in breathing,Infection probability
339,101,0,73,0,1,1,0,0
340,101,0,97,0,1,0,-1,0
341,101,1,89,0,1,1,0,1
342,100,1,41,1,0,0,-1,0
343,98,1,33,0,0,0,-1,1

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fever                    344 non-null    int64
 1   Body Pain                344 non-null    int64
 2   Age                      344 non-null    int64
 3   Lost of smell or taste   344 non-null    int64
 4   Sore throat              344 non-null    int64
 5   headache                 344 non-null    int64
 6   Difficulty in breathing  344 non-null    int64
 7   Infection probability    344 non-null    int64
dtypes: int64(8)
memory usage: 21.6 KB

In [60]:
df["headache"].value_counts()

0    179
1    165
Name: headache, dtype: int64

In [61]:
df.describe()

,Fever,Body Pain,Age,Lost of smell or taste,Sore throat,headache,Difficulty in breathing,Infection probability
count,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000
mean,101.139535,0.500000,52.802326,0.497093,0.575581,0.479651,0.002907,0.485465
std,1.998033,0.500728,29.558094,0.500720,0.494974,0.500313,0.813510,0.500517
min,98.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000
25%,99.000000,0.000000,29.000000,0.000000,0.000000,0.000000,-1.000000,0.000000
50%,101.000000,0.500000,49.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,103.000000,1.000000,80.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,104.000000,1.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [62]:
import numpy as np

In [63]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffuled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffuled[:test_set_size]
    train_indices=shuffuled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [64]:
train,test=data_split(df,0.2)

In [65]:
train

,Fever,Body Pain,Age,Lost of smell or taste,Sore throat,headache,Difficulty in breathing,Infection probability
16,99,0,23,0,1,0,-1,1
66,102,1,67,0,0,0,-1,0
229,104,0,65,1,1,0,0,0
7,98,0,49,1,1,0,-1,0
140,102,0,6,1,0,0,0,0
...,...,...,...,...,...,...,...,...
188,98,0,4,0,1,1,0,1
71,98,0,76,0,0,1,-1,0
106,103,1,72,1,0,1,-1,1
270,103,1,53,0,0,0,1,1
102,103,1,1,0,1,0,-1,1

In [66]:
test

,Fever,Body Pain,Age,Lost of smell or taste,Sore throat,headache,Difficulty in breathing,Infection probability
194,102,1,53,1,0,1,1,0
157,104,0,45,1,1,1,1,0
225,99,0,84,1,1,1,-1,1
208,100,1,93,1,0,1,-1,1
318,103,0,52,0,1,1,1,0
...,...,...,...,...,...,...,...,...
45,102,0,35,1,1,0,1,1
321,99,0,1,0,0,1,0,1
172,101,0,76,1,0,1,1,0
73,101,0,6,0,0,1,0,0
76,104,1,91,1,0,1,1,0

In [67]:
X_train=train[['Fever','Body Pain','Age','Lost of smell or taste','Sore throat','headache','Difficulty in breathing']]
X_test=test[['Fever','Body Pain','Age','Lost of smell or taste','Sore throat','headache','Difficulty in breathing']]

In [68]:
X_train.to_numpy()

array([[ 99,   0,  23, ...,   0,  -1,   1],
       [102,   1,  67, ...,   0,  -1,   0],
       [104,   0,  65, ...,   0,   0,   0],
       ...,
       [103,   1,  72, ...,   1,  -1,   1],
       [103,   1,  53, ...,   0,   1,   1],
       [103,   1,   1, ...,   0,  -1,   1]], dtype=int64)

In [69]:
Y_train=train[['Infection probability']].to_numpy().reshape(276 ,)
Y_test=test[['Infection probability']].to_numpy().reshape(68,)

In [70]:
Y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [71]:
Y_test

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0], dtype=int64)

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
clf=LogisticRegression()

In [74]:
clf.fit(X_train,Y_train)

LogisticRegression()

In [77]:
infprob=clf.predict_proba([[100,1,22,1,1,0,1,1]])[0][1]

C:\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [78]:
infprob

0.9577024895469214